[View in Colaboratory](https://colab.research.google.com/github/JackRuby520/AI_and_security/blob/master/tfnumpy.ipynb)

In [2]:
def matrixMul(A, B):
    res = [[0] * len(B[0]) for i in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                res[i][j] += A[i][k] * B[k][j]
    return res

def matrixMul2(A, B):
    return [[sum(a * b for a, b in zip(a, b)) for b in zip(*B)] for a in A]

a = [[1,2], [3,4], [5,6], [7,8]]
b = [[1,2,3,4], [5,6,7,8]]

from numpy import dot
print(list,dot(a,b))
print(list,dot(b,a))

<class 'list'> [[11 14 17 20]
 [23 30 37 44]
 [35 46 57 68]
 [47 62 77 92]]
<class 'list'> [[ 50  60]
 [114 140]]


TensorFlow矩陣相乘